/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasm_free: (a: number, b: number) => void;
export const parseFontInfo: (a: number, b: number) => [number, number, number];
export const wasm_all_page_info: (a: number, b: number, c: number) => [number, number, number];
export const wasm_authenticate: (a: number, b: number, c: number, d: number, e: number) => number;
export const wasm_disable_telemetry: (a: number) => number;
export const wasm_document_format: (a: number, b: number, c: number) => [number, number];
export const wasm_enableGoogleFonts: (a: number) => void;
export const wasm_get_all_annotations: (a: number, b: number, c: number) => [number, number, number];
export const wasm_get_bytes: (a: number, b: number, c: number) => [number, number, number, number];
export const wasm_get_font_usage: (a: number, b: number, c: number) => [number, number, number];
export const wasm_get_layout_page: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasm_get_outline: (a: number, b: number, c: number) => [number, number, number];
export const wasm_get_page_annotations: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasm_has_document: (a: number, b: number, c: number) => number;
export const wasm_init_gpu: (a: number) => number;
export const wasm_license_status: (a: number) => [number, number, number];
export const wasm_load: (a: number, b: number, c: number) => [number, number, number, number];
export const wasm_needs_password: (a: number, b: number, c: number) => number;
export const wasm_new: (a: number, b: number, c: number, d: number) => number;
export const wasm_page_count: (a: number, b: number, c: number) => number;
export const wasm_page_groups: (a: number, b: number, c: number) => [number, number, number];
export const wasm_page_info: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasm_pdf_compose: (a: number, b: any, c: any) => [number, number, number];
export const wasm_pdf_compress: (a: number, b: number, c: number) => [number, number, number, number];
export const wasm_pdf_extract_fonts: (a: number, b: number, c: number) => [number, number, number];
export const wasm_pdf_extract_images: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasm_pdf_save_annotations: (a: number, b: number, c: number, d: any) => [number, number, number, number];
export const wasm_pdf_split_by_outline: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasm_registerFonts: (a: number, b: any) => void;
export const wasm_remove_document: (a: number, b: number, c: number) => number;
export const wasm_render_page_gpu: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const wasm_render_page_to_rgba: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const wasm_set_license: (a: number, b: number, c: number) => [number, number, number];
export const wasm_set_visibility_group_visible: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const wasm_setup_telemetry: (a: number, b: number, c: number) => void;
export const wasm_pdf_decompress: (a: number, b: number, c: number) => [number, number, number, number];
export const wasm_get_visibility_groups: (a: number, b: number, c: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
